[airshipper]

[appimage-builder]

[bat]

[bats]

[bitwarden-bin]
blocked-archs = ["arm64"]

[cargo-appimage]

[celeste]
blocked-distros = ["focal", "jammy", "bullseye"]

[chezmoi]

[cloudflared]

[cloudflare-warp]

[code-bin]

[comb]

[dasel]

[deno]

[discord]

[docuum]

[docker-compose]

[doppler]

[drone-cli]

[drone-runner-exec]

[element-desktop-bin]

[exa]

[fd]

[golang-go]

[golang-go-bin]

[gh]

[glab]

[glow]

[google-chrome-stable]
blocked-archs = ["arm64"]

[hugo]

[hyperfine]

[just]

[makedeb]

[makedeb-beta]

[makedeb-alpha]

[mari]

[matrix-commander-rs]

[maturin]

[mcrcon]

[minecraft-launcher]

[mist]

[mpr-cli]

[mprocs]

[neovim]

[nodejs]

[npm]
blocked-distros = ["focal"]

[parse-changelog]

[pg]

[polybar]

[prismlauncher]

[proton-ge-custom-bin]
blocked-distros = ["bullseye"]

[rclone]

[ripgrep]

[rustc]
blocked-archs = ["arm64"]

[rustup]

[rustup-init]

[sentry-cli]

[starship]

[tap]

[toast]

[tokei]

[woeusb-ng]

[xtr]

[zoxide]

# vim: set sw=4 expandtab:
