[airshipper]

[appimage-builder]

[bat]

[bats]

[bitwarden-bin]

[celeste]
blocked_distros = ["focal", "bullseye"]

[chezmoi]

[code-bin]

[comb]

[dasel]

[deno]

[discord]

[docuum]

[docker-compose]

[drone-cli]

[drone-runner-exec]

[element-desktop-bin]

[exa]

[fd]

[golang-go]

[gh]

[glab]

[glow]

[hugo]

[hyperfine]

[just]

[makedeb]

[makedeb-beta]

[makedeb-alpha]

[mari]

[matrix-commander-rs]

[maturin]

[mcrcon]

[mist]

[mpr-cli]

[mprocs]

[neovim]

[nodejs]

[npm]

[pacstall]

[parse-changelog]

[pg]

[polybar]

[prismlauncher]

[proton-ge-custom-bin]
blocked_distros = ["bullseye"]

[rclone]

[ripgrep]

[rustc]

[rustup]

[sentry-cli]

[starship]

[tap]

[toast]

[tokei]

[xtr]

[zoxide]

# vim: set sw=4 expandtab:
